image: node:lts-alpine

include:
  - template: SAST.gitlab-ci.yml

stages:
  - tests
  - security
  - publish

code quality:
  stage: tests
  script:
    - yarn install
    - yarn run lint

dependencies outdated:
  stage: tests
  script:
    - yarn install
    - yarn outdated
  allow_failure: true

tests & coverage:
  stage: tests
  script:
    - yarn install
    - yarn test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/

dependencies check:
  stage: security
  needs: &tests-jobs
    - code quality
    - dependencies outdated
    - tests & coverage
  dependencies: *tests-jobs
  script:
    - yarn audit --production

sast:
  stage: security
  needs: *tests-jobs
  dependencies: *tests-jobs

pages:
  stage: publish
  needs: &security-jobs
    - dependencies check
    - eslint-sast
    - nodejs-scan-sast
    - semgrep-sast
  dependencies: *security-jobs
  script:
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
  only:
    - master
  environment:
    name: coverage report
    url: https://vuedoc.gitlab.io/parser

package:
  stage: publish
  needs: *security-jobs
  dependencies: *security-jobs
  script:
    - yarn pack
  artifacts:
    paths:
      - ./*.tgz

publish:
  stage: publish
  needs: *security-jobs
  dependencies: *security-jobs
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - yarn publish
  environment:
    name: npm
    url: https://www.npmjs.com/package/@vuedoc/parser
